### ISSUE TITLE
output size does not match input size when padding=True

### ISSUE THREAD

**Issue by yi-li-yang** [jvanvugt/pytorch-unet#2]
Hi, I input a image (1646,1646) into the unet, and assigned padding=True, but the output is (1632,1632), may I ask why and how to make the size unified?

**Comment by jvanvugt** [comment]
It is because the input sizes are divided by 2 (and floored) in each pooling layer. 1646 is divisible by 2 only once. You should either crop or pad your input images such that they are a multiple of `2^(depth-1)`. By the way 1646 is already ridiculously large. It might be a good idea to downsample or train on crops of the original image.
